const tintColorLight = "#2f95dc";
const tintColorDark = "#fff";

export default {
  light: {
    text: "#000",
    background: "#fff",
    tint: tintColorLight,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#fff",
    background: "#000",
    tint: tintColorDark,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorDark,
  },
};

export const lightColorsAuth = {
  background: "bg-white",
  primaryBackground: "bg-white",
  secondaryBackground: "bg-gray-100",
  text: "text-black",
  primaryText: "text-black",
  secondaryText: "text-gray-600",
  border: "border-black",
  buttonBackground: "bg-yellow-400",
  activityIndicatorColor: "#000000",
  inputBackground: "bg-gray-100",
  inputBorder: "border-gray-300",
  inputPlaceholder: "text-gray-400",
  buttonText: "text-black",
  errorText: "text-red-500",
};

export const darkColorsAuth = {
  background: "bg-black",
  primaryBackground: "bg-gray-900",
  secondaryBackground: "bg-gray-800",
  text: "text-white",
  primaryText: "text-white",
  secondaryText: "text-gray-400",
  border: "border-white",
  buttonBackground: "bg-yellow-600",
  activityIndicatorColor: "#FFFFFF",
  inputBackground: "bg-gray-800",
  inputBorder: "border-gray-600",
  inputPlaceholder: "text-gray-400",
  buttonText: "text-white",
  errorText: "text-red-500",
};

export const lightColorsExercise = {
  background: "bg-gray-100",
  primaryBackground: "bg-white",
  secondaryBackground: "bg-gray-200",
  text: "text-black",
  primaryText: "text-black",
  secondaryText: "text-gray-500",
  buttonBorder: "border-black",
  border: "border-gray-300",
  buttonBackground: "bg-yellow-400",
  buttonText: "text-black",
  inputBackground: "bg-white",
  inputBorder: "border-gray-300",
  inputPlaceholder: "text-gray-400",
  cancelButtonBackground: "bg-gray-300",
  cancelButtonText: "text-gray-700",
  errorText: "text-red-500",

  modalBackground: "bg-white",
  modalText: "text-black",
  //cancelButtonBackground: "bg-gray-300",
  cancelButtonBorder: "border-gray-400",
  //cancelButtonText: "text-gray-700",
  deleteButtonBackground: "bg-red-500",
  deleteButtonBorder: "border-red-700",
  deleteButtonText: "text-white",
  holdingBackground: "bg-yellow-200",
};

export const darkColorsExercise = {
  background: "bg-black",
  primaryBackground: "bg-gray-700",
  secondaryBackground: "bg-gray-800",
  text: "text-white",
  primaryText: "text-white",
  secondaryText: "text-gray-400",
  buttonBorder: "border-white",
  border: "border-gray-600",
  buttonBackground: "bg-yellow-600",
  buttonText: "text-white",
  inputBackground: "bg-gray-700",
  inputBorder: "border-gray-600",
  inputPlaceholder: "text-gray-400",
  cancelButtonBackground: "bg-gray-600",
  cancelButtonText: "text-gray-200",
  errorText: "text-red-500",

  modalBackground: "bg-gray-800",
  modalText: "text-white",
  //cancelButtonBackground: "bg-gray-600",
  cancelButtonBorder: "border-gray-700",
  //cancelButtonText: "text-gray-200",
  deleteButtonBackground: "bg-red-700",
  deleteButtonBorder: "border-red-900",
  deleteButtonText: "text-white",
  holdingBackground: "bg-yellow-700",
};
